/*
 *
 * Helper: `fetchZatcaCompliance`.
 *
 */

import createZatcaRequest from "./createZatcaRequest.mjs";
import {
  BASE_API_HEADERS,
  SERVER_CONFIG,
  API_IDS_NAMES,
} from "../constants.mjs";

const { otp } = SERVER_CONFIG;
const { POST_ZATCA_COMPLIANCE } = API_IDS_NAMES;

// after final csid
// invoices/reporting/single for simplified
// invoices/clearance/single for standard

const fetchZatcaCompliance = async (encodedPayerTaxCert) => {
  const bodyData = {
    csr: encodedPayerTaxCert,
  };

  const requestHeaders = {
    ...BASE_API_HEADERS,
    "Accept-Version": "V2",
    OTP: otp,
  };

  const response = await createZatcaRequest({
    resourceName: POST_ZATCA_COMPLIANCE,
    bodyData,
    requestHeaders,
  });

  return response;
};

export default fetchZatcaCompliance;

// tax encod
// LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQnZqQ0NBV1FDQVFBd1RERUxNQWtHQTFVRUJoTUNVMEV4RXpBUkJnTlZCQXNNQ2pNd01EQTFOams0TlRFeApFekFSQmdOVkJBb01Da2xqWTNOcGNHOXlaWGd4RXpBUkJnTlZCQU1NQ2tsalkzTnBjRzl5Wlhnd1ZqQVFCZ2NxCmhrak9QUUlCQmdVcmdRUUFDZ05DQUFSNmJoYXNqRHAxdlg1d3pYemxUYWtNc3BLMVE3ZkFJYjg3OW9xbXNmZVYKYURuMXNOdmNOTFlGaU5nYW9GaEdDL3hxS0paV1piQVBMaXE5czVYaDNtcnZvSUc0TUlHMUJna3Foa2lHOXcwQgpDUTR4Z2Fjd2dhUXdKQVlKS3dZQkJBR0NOeFFDQkJjVEZWQlNSVnBCVkVOQkxVTnZaR1V0VTJsbmJtbHVaekI4CkJnTlZIUkVFZFRCenBIRXdiekVnTUI0R0ExVUVCQXdYTVMxVGFHRkZhM3d5TFZOb1lVVnJmRE10VTJoaFJXc3gKSHpBZEJnb0praWFKay9Jc1pBRUJEQTh6TURBd05UWTVPRFV4TURBd01ETXhEVEFMQmdOVkJBd01CREV4TURBeApDekFKQmdOVkJCb01BbE5CTVE0d0RBWURWUVFQREFWVFlXeGxjekFLQmdncWhrak9QUVFEQWdOSUFEQkZBaUJTCk9SSHBHaWtTWGRCQ0xMaXZGSW9ManJ6cHVXTUN0djZGSTZmU1hlWlErd0loQUo0ZnFMV1RHMm5wOUZnOXpXQWEKREJLUU1sQlBTV2VyZk1zWTVxWlZRSGd4Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQ==

// {
//   "requestID": 1234567890123,
//   "dispositionMessage": "ISSUED",
//   "binarySecurityToken": "TUlJQjR6Q0NBWWlnQXdJQkFnSUdBWXZZQ2xFdk1Bb0dDQ3FHU000OUJBTUNNQlV4RXpBUkJnTlZCQU1NQ21WSmJuWnZhV05wYm1jd0hoY05Nak14TVRFMk1USXhNRE14V2hjTk1qZ3hNVEUxTWpFd01EQXdXakJNTVFzd0NRWURWUVFHRXdKVFFURVRNQkVHQTFVRUN3d0tNekF3TURVMk9UZzFNVEVUTUJFR0ExVUVDZ3dLU1dOamMybHdiM0psZURFVE1CRUdBMVVFQXd3S1NXTmpjMmx3YjNKbGVEQldNQkFHQnlxR1NNNDlBZ0VHQlN1QkJBQUtBMElBQkhwdUZxeU1Pblc5Zm5ETmZPVk5xUXl5a3JWRHQ4QWh2enYyaXFheDk1Vm9PZld3Mjl3MHRnV0kyQnFnV0VZTC9Hb29sbFpsc0E4dUtyMnpsZUhlYXUramdZOHdnWXd3REFZRFZSMFRBUUgvQkFJd0FEQjhCZ05WSFJFRWRUQnpwSEV3YnpFZ01CNEdBMVVFQkF3WE1TMVRhR0ZGYTN3eUxWTm9ZVVZyZkRNdFUyaGhSV3N4SHpBZEJnb0praWFKay9Jc1pBRUJEQTh6TURBd05UWTVPRFV4TURBd01ETXhEVEFMQmdOVkJBd01CREV4TURBeEN6QUpCZ05WQkJvTUFsTkJNUTR3REFZRFZRUVBEQVZUWVd4bGN6QUtCZ2dxaGtqT1BRUURBZ05KQURCR0FpRUF2YTlsNzVLdlplVExBWEtFQWxQeGpTd0ROYU1JQzY1TjlrMmtSNTFNTDlBQ0lRRHNINTJYUnJnS2JnWm1ZRXltZWgxQkVBMFFxbDFJTVhyMTFuQUJvZ2IwNWc9PQ==",
//   "secret": "vp7z8hgLZgyYNgSCA2ZpdUe8bq6JdZ94GkU+ZVkxDgY=",
//   "errors": null
// }
